//---------Auth Action Constants--------------
export const ADD_EMAIL = Symbol('ADD_EMAIL');
export const ADD_PASSWORD = Symbol('ADD_PASSWORD');
export const LOGIN_SUBMIT = Symbol('LOGIN_SUBMIT');
export const LOGIN_SUCCESS = Symbol('LOGIN_SUCCESS');
export const LOGIN_FAILURE = Symbol('LOGIN_FAILURE');
export const SIGNUP_FIRST_NAME = Symbol('SIGNUP_FIRST_NAME');
export const SIGNUP_LAST_NAME = Symbol('SIGNUP_LAST_NAME');
export const SIGNUP_SUBMIT = Symbol('SIGNUP_SUBMIT');
export const SIGNUP_SUCCESS = Symbol('SIGNUP_SUCCESS');
export const SIGNUP_FAILURE = Symbol('SIGNUP_FAILURE');
export const LOGOUT_SUBMIT = Symbol('LOGOUT_SUBMIT');
export const LOGOUT_SUCCESS = Symbol('LOGOUT_SUCCESS');
export const LOGOUT_FAILURE = Symbol('LOGOUT_FAILURE');

// location actions
export const GET_USERS_LOCATIONS = Symbol('GET_USERS_LOCATIONS');
export const GET_USERS_LOCATIONS_SUCCESS = Symbol('GET_USERS_LOCATIONS_SUCCESS');
export const GET_USERS_LOCATIONS_ERROR = Symbol('GET_USERS_LOCATIONS_ERROR');
export const GET_LOCATIONS_USERS = Symbol('GET_LOCATIONS_USERS');
export const GET_LOCATIONS_USERS_SUCCESS = Symbol('GET_LOCATIONS_USERS_SUCCESS');
export const GET_LOCATIONS_USERS_ERROR = Symbol('GET_LOCATIONS_USERS_ERROR');
export const SUBMIT_NEW_LOCATION = Symbol('SUBMIT_NEW_LOCATION');
export const SUBMIT_NEW_LOCATION_SUCCESS = Symbol('SUBMIT_NEW_LOCATION_SUCCESS');
export const SUBMIT_NEW_LOCATION_ERROR = Symbol('SUBMIT_NEW_LOCATION_ERROR');
export const UPDATE_LOCATION = Symbol('UPDATE_LOCATION');
export const UPDATE_LOCATION_SUCCESS = Symbol('UPDATE_LOCATION_SUCCESS');
export const UPDATE_LOCATION_ERROR = Symbol('UPDATE_LOCATION_ERROR');
export const DELETE_LOCATION = Symbol('DELETE_LOCATION');
export const DELETE_LOCATION_SUCCESS = Symbol('DELETE_LOCATION_SUCCESS');
export const DELETE_LOCATION_ERROR = Symbol('DELETE_LOCATION_ERROR');

// 