//---------Auth Action Constants--------------
export const ADD_EMAIL = 'ADD_EMAIL';
export const ADD_PASSWORD = 'ADD_PASSWORD';
export const LOGIN_SUBMIT = 'LOGIN_SUBMIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_FIRST_NAME = 'SIGNUP_FIRST_NAME';
export const SIGNUP_LAST_NAME = 'SIGNUP_LAST_NAME';
export const SIGNUP_SUBMIT = 'SIGNUP_SUBMIT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGOUT_SUBMIT = 'LOGOUT_SUBMIT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// DATA actions
// location actions
export const GET_USERS_LOCATIONS = 'GET_USERS_LOCATIONS';
export const GET_USERS_LOCATIONS_SUCCESS = 'GET_USERS_LOCATIONS_SUCCESS';
export const GET_USERS_LOCATIONS_ERROR = 'GET_USERS_LOCATIONS_ERROR';

export const GET_LOCATIONS_USERS = 'GET_LOCATIONS_USERS';
export const GET_LOCATIONS_USERS_SUCCESS = 'GET_LOCATIONS_USERS_SUCCESS';
export const GET_LOCATIONS_USERS_ERROR = 'GET_LOCATIONS_USERS_ERROR';

export const SUBMIT_NEW_LOCATION = 'SUBMIT_NEW_LOCATION';
export const SUBMIT_NEW_LOCATION_SUCCESS = 'SUBMIT_NEW_LOCATION_SUCCESS';
export const SUBMIT_NEW_LOCATION_ERROR = 'SUBMIT_NEW_LOCATION_ERROR';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_ERROR = 'UPDATE_LOCATION_ERROR';

export const DELETE_LOCATION = 'DELETE_LOCATION';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_ERROR = 'DELETE_LOCATION_ERROR';

// room actions
export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_ERROR = 'GET_ROOMS_ERROR';

export const POST_ROOM = 'POST_ROOM';
export const POST_ROOM_SUCCESS = 'POST_ROOM_SUCCESS';
export const POST_ROOM_ERROR = 'POST_ROOM_ERROR';

export const UPDATE_ROOM = 'UPDATE_ROOM';
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
export const UPDATE_ROOM_ERROR = 'UPDATE_ROOM_ERROR';

export const DELETE_ROOM = 'DELETE_ROOM';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_ERROR = 'DELETE_ROOM_ERROR';

// reservations
// for the calendar
export const GET_ALL_RESERVATIONS = 'GET_ALL_RESERVATIONS';
export const GET_ALL_RESERVATIONS_SUCCESS = 'GET_ALL_RESERVATIONS_SUCCESS';
export const GET_ALL_RESERVATIONS_ERROR = 'GET_ALL_RESERVATIONS_ERROR';

export const GET_ROOMS_RESERVATIONS = 'GET_ROOMS_RESERVATIONS';
export const GET_ROOMS_RESERVATIONS_SUCCESS = 'GET_ROOMS_RESERVATIONS_SUCCESS';
export const GET_ROOMS_RESERVATIONS_ERROR = 'GET_ROOMS_RESERVATIONS_ERROR';

export const POST_RESERVATION = 'POST_RESERVATION';
export const POST_RESERVATION_SUCCESS = 'POST_RESERVATION_SUCCESS';
export const POST_RESERVATION_ERROR = 'POST_RESERVATION_ERROR';

export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const UPDATE_RESERVATION_SUCCESS = 'UPDATE_RESERVATION_SUCCESS';
export const UPDATE_RESERVATION_ERROR = 'UPDATE_RESERVATION_ERROR';

export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const DELETE_RESERVATION_SUCCESS = 'DELETE_RESERVATION_SUCCESS';
export const DELETE_RESERVATION_ERROR = 'DELETE_RESERVATION_ERROR';