//---------Auth Action Constants--------------
export const ADD_EMAIL = 'ADD_EMAIL';
export const ADD_PASSWORD = 'ADD_PASSWORD';
export const LOGIN_SUBMIT = 'LOGIN_SUBMIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_FIRST_NAME = 'SIGNUP_FIRST_NAME';
export const SIGNUP_LAST_NAME = 'SIGNUP_LAST_NAME';
export const SIGNUP_SUBMIT = 'SIGNUP_SUBMIT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGOUT_SUBMIT = 'LOGOUT_SUBMIT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// location actions
export const GET_USERS_LOCATIONS = 'GET_USERS_LOCATIONS';
export const GET_USERS_LOCATIONS_SUCCESS = 'GET_USERS_LOCATIONS_SUCCESS';
export const GET_USERS_LOCATIONS_ERROR = 'GET_USERS_LOCATIONS_ERROR';
export const GET_LOCATIONS_USERS = 'GET_LOCATIONS_USERS';
export const GET_LOCATIONS_USERS_SUCCESS = 'GET_LOCATIONS_USERS_SUCCESS';
export const GET_LOCATIONS_USERS_ERROR = 'GET_LOCATIONS_USERS_ERROR';
export const SUBMIT_NEW_LOCATION = 'SUBMIT_NEW_LOCATION';
export const SUBMIT_NEW_LOCATION_SUCCESS = 'SUBMIT_NEW_LOCATION_SUCCESS';
export const SUBMIT_NEW_LOCATION_ERROR = 'SUBMIT_NEW_LOCATION_ERROR';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_ERROR = 'UPDATE_LOCATION_ERROR';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_ERROR = 'DELETE_LOCATION_ERROR';

// 